<?php

namespace ContainerQHpifF4;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_JtGX1EDService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.JtGX1ED' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.JtGX1ED'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'messageRepository' => ['privates', '.errored.fV.2kTh', NULL, 'Cannot determine controller argument for "App\\Controller\\UserController::index()": the $messageRepository argument is type-hinted with the non-existent class or interface: "App\\Controller\\MessageRepository". Did you forget to add a use statement?'],
        ], [
            'messageRepository' => '?',
        ]);
    }
}
