<?php

namespace ContainerQHpifF4;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_Errored_FV_2kThService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored.fV.2kTh' shared service.
     *
     * @return \App\Controller\MessageRepository
     */
    public static function do($container, $lazyLoad = true)
    {
        $container->throw('Cannot determine controller argument for "App\\Controller\\UserController::index()": the $messageRepository argument is type-hinted with the non-existent class or interface: "App\\Controller\\MessageRepository". Did you forget to add a use statement?');
    }
}
