<?php

namespace ContainerX95EEz4;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_R7OaP6GService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.R7OaP6G' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.R7OaP6G'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'entityManager' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', false],
            'message' => ['privates', '.errored..service_locator.R7OaP6G.App\\Entity\\Message', NULL, 'Cannot autowire service ".service_locator.R7OaP6G": it references class "App\\Entity\\Message" but no such service exists.'],
        ], [
            'entityManager' => '?',
            'message' => 'App\\Entity\\Message',
        ]);
    }
}
