<?php

namespace ContainerX95EEz4;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_RKXSkGJService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.RKXSkGJ' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.RKXSkGJ'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'validation' => ['privates', '.errored..service_locator.RKXSkGJ.App\\Entity\\Validation', NULL, 'Cannot autowire service ".service_locator.RKXSkGJ": it references class "App\\Entity\\Validation" but no such service exists.'],
        ], [
            'validation' => 'App\\Entity\\Validation',
        ]);
    }
}
