<?php

namespace Proxies\__CG__\App\Entity;


/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Competition extends \App\Entity\Competition implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Proxy\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Proxy\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array<string, null> properties to be lazy loaded, indexed by property name
     */
    public static $lazyPropertiesNames = array (
);

    /**
     * @var array<string, mixed> default values of properties to be lazy loaded, with keys being the property names
     *
     * @see \Doctrine\Common\Proxy\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = array (
);



    public function __construct(?\Closure $initializer = null, ?\Closure $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return ['__isInitialized__', '' . "\0" . 'App\\Entity\\Competition' . "\0" . 'id', '' . "\0" . 'App\\Entity\\Competition' . "\0" . 'title', '' . "\0" . 'App\\Entity\\Competition' . "\0" . 'dateDeb', '' . "\0" . 'App\\Entity\\Competition' . "\0" . 'dateFin', '' . "\0" . 'App\\Entity\\Competition' . "\0" . 'type', '' . "\0" . 'App\\Entity\\Competition' . "\0" . 'nbp', '' . "\0" . 'App\\Entity\\Competition' . "\0" . 'id_uc', '' . "\0" . 'App\\Entity\\Competition' . "\0" . 'gifts', '' . "\0" . 'App\\Entity\\Competition' . "\0" . 'userPart'];
        }

        return ['__isInitialized__', '' . "\0" . 'App\\Entity\\Competition' . "\0" . 'id', '' . "\0" . 'App\\Entity\\Competition' . "\0" . 'title', '' . "\0" . 'App\\Entity\\Competition' . "\0" . 'dateDeb', '' . "\0" . 'App\\Entity\\Competition' . "\0" . 'dateFin', '' . "\0" . 'App\\Entity\\Competition' . "\0" . 'type', '' . "\0" . 'App\\Entity\\Competition' . "\0" . 'nbp', '' . "\0" . 'App\\Entity\\Competition' . "\0" . 'id_uc', '' . "\0" . 'App\\Entity\\Competition' . "\0" . 'gifts', '' . "\0" . 'App\\Entity\\Competition' . "\0" . 'userPart'];
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (Competition $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy::$lazyPropertiesDefaults as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', []);
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load(): void
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', []);
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized(): bool
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized): void
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null): void
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer(): ?\Closure
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null): void
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner(): ?\Closure
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @deprecated no longer in use - generated code now relies on internal components rather than generated public API
     * @static
     */
    public function __getLazyProperties(): array
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getId(): ?int
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', []);

        return parent::getId();
    }

    /**
     * {@inheritDoc}
     */
    public function getTitle(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTitle', []);

        return parent::getTitle();
    }

    /**
     * {@inheritDoc}
     */
    public function setTitle(string $title): \App\Entity\Competition
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setTitle', [$title]);

        return parent::setTitle($title);
    }

    /**
     * {@inheritDoc}
     */
    public function getDateDeb(): ?\DateTimeInterface
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDateDeb', []);

        return parent::getDateDeb();
    }

    /**
     * {@inheritDoc}
     */
    public function setDateDeb(\DateTimeInterface $dateDeb): \App\Entity\Competition
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDateDeb', [$dateDeb]);

        return parent::setDateDeb($dateDeb);
    }

    /**
     * {@inheritDoc}
     */
    public function getDateFin(): ?\DateTimeInterface
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDateFin', []);

        return parent::getDateFin();
    }

    /**
     * {@inheritDoc}
     */
    public function setDateFin(\DateTimeInterface $dateFin): \App\Entity\Competition
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDateFin', [$dateFin]);

        return parent::setDateFin($dateFin);
    }

    /**
     * {@inheritDoc}
     */
    public function getType(): ?int
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getType', []);

        return parent::getType();
    }

    /**
     * {@inheritDoc}
     */
    public function setType(int $type): \App\Entity\Competition
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setType', [$type]);

        return parent::setType($type);
    }

    /**
     * {@inheritDoc}
     */
    public function getNbp(): ?int
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getNbp', []);

        return parent::getNbp();
    }

    /**
     * {@inheritDoc}
     */
    public function setNbp(int $nbp): \App\Entity\Competition
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setNbp', [$nbp]);

        return parent::setNbp($nbp);
    }

    /**
     * {@inheritDoc}
     */
    public function getIdUc(): ?int
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getIdUc', []);

        return parent::getIdUc();
    }

    /**
     * {@inheritDoc}
     */
    public function setIdUc(int $id_uc): \App\Entity\Competition
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setIdUc', [$id_uc]);

        return parent::setIdUc($id_uc);
    }

    /**
     * {@inheritDoc}
     */
    public function getGifts(): \Doctrine\Common\Collections\Collection
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getGifts', []);

        return parent::getGifts();
    }

    /**
     * {@inheritDoc}
     */
    public function addGift(\App\Entity\Gifts $gift): \App\Entity\Competition
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addGift', [$gift]);

        return parent::addGift($gift);
    }

    /**
     * {@inheritDoc}
     */
    public function removeGift(\App\Entity\Gifts $gift): \App\Entity\Competition
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeGift', [$gift]);

        return parent::removeGift($gift);
    }

    /**
     * {@inheritDoc}
     */
    public function __toString(): string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, '__toString', []);

        return parent::__toString();
    }

    /**
     * {@inheritDoc}
     */
    public function getUserPart(): \Doctrine\Common\Collections\Collection
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getUserPart', []);

        return parent::getUserPart();
    }

    /**
     * {@inheritDoc}
     */
    public function addUserPart(\App\Entity\User $userPart): \App\Entity\Competition
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addUserPart', [$userPart]);

        return parent::addUserPart($userPart);
    }

    /**
     * {@inheritDoc}
     */
    public function removeUserPart(\App\Entity\User $userPart): \App\Entity\Competition
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeUserPart', [$userPart]);

        return parent::removeUserPart($userPart);
    }

}
