<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerXxjLUTI\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerXxjLUTI/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerXxjLUTI.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerXxjLUTI\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerXxjLUTI\App_KernelDevDebugContainer([
    'container.build_hash' => 'XxjLUTI',
    'container.build_id' => '03b7d246',
    'container.build_time' => 1681462421,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerXxjLUTI');
