<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerHttEt9n\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerHttEt9n/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerHttEt9n.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerHttEt9n\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerHttEt9n\App_KernelDevDebugContainer([
    'container.build_hash' => 'HttEt9n',
    'container.build_id' => 'f3172e30',
    'container.build_time' => 1681924228,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerHttEt9n');
