<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerX2sEDTC\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerX2sEDTC/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerX2sEDTC.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerX2sEDTC\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerX2sEDTC\App_KernelDevDebugContainer([
    'container.build_hash' => 'X2sEDTC',
    'container.build_id' => '36d288b4',
    'container.build_time' => 1681880680,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerX2sEDTC');
